server:
  port: 8001

spring:
  application:
    name: ToDoList
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view=false:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  file:
    name: log/app.log
    path: logs
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.todolist: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
