name: Build Full Stack App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      
    - name: Checkout Repository
      uses: actions/checkout@v4

    # ---------- FRONTEND ----------
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Frontend Dependencies (with legacy peer deps)
      working-directory: frontend
      run: npm install --legacy-peer-deps

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    # ---------- BACKEND ----------
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Backend with Maven (Skip Tests)
      working-directory: backend/ToDoList
      run: mvn clean install -DskipTests
